name: tide

services:
  alpine-pinned:
    build:
      context: build/context
      dockerfile: ../Dockerfile
      tags:
        - ${REGISTRY_HOST}:${REGISTRY_PORT}/${ALPINE_PINNED_IMAGE_NAME}
    image: ${REGISTRY_HOST}:${REGISTRY_PORT}/${ALPINE_PINNED_IMAGE_NAME}
