name: tide
# TODO: replace all `localhost` with ${REGISTRY_HOST}
services:
  non-root-user:
    build:
      args:
        ALPINE_PINNED_IMAGE: localhost:${REGISTRY_PORT}/${ALPINE_PINNED_IMAGE_NAME}
        NON_ROOT_USER_GID: ${NON_ROOT_USER_GID}
        NON_ROOT_USER_NAME: ${NON_ROOT_USER_NAME}
        NON_ROOT_USER_UID: ${NON_ROOT_USER_UID}
      context: build/context
      dockerfile: ../Dockerfile
      tags:
        - localhost:${REGISTRY_PORT}/${NON_ROOT_USER_IMAGE_NAME}
    image: localhost:${REGISTRY_PORT}/${NON_ROOT_USER_IMAGE_NAME}
