#!/bin/env bash

TIDE_INSTALL_DIR="${TIDE_INSTALL_DIR:-$HOME/.tide/}"
TIDE_URL="${TIDE_URL:-https://raw.githubusercontent.com/m374-crypt0/tide/refs/heads/main/}"

ensure_shell_is_bash() {
  if [ "$(basename "$SHELL")" != 'bash' ]; then
    echo bash required >&2
    return 1
  fi
}

install() {
  local file && file="$1"

  curl \
    -L "${TIDE_URL}src/${file}" \
    --create-dirs \
    --output "${TIDE_INSTALL_DIR}${file}" &&
    chmod +x "${TIDE_INSTALL_DIR}${file}"
}

main() {
  ensure_shell_is_bash &&
    install tide &&
    install tideup
}

main
