#!/bin/env bash

# NOTE: modify this variable at your convenience
TIDE_INSTALL_DIR="${TIDE_INSTALL_DIR:-$HOME/.tide/}"

# NOTE: fork friendly
TIDE_URL="${TIDE_URL:-https://raw.githubusercontent.com/m374-crypt0/tide/refs/heads/main/}"

# NOTE: useful for testing purposes
BASHRC_PATH="${BASHRC_PATH:-${HOME}/.bashrc}"

ensure_shell_is_bash() {
  if [ "$(basename "$SHELL")" != 'bash' ]; then
    echo bash required >&2
    return 1
  fi
}

install_tideup() {
  curl \
    -L "${TIDE_URL}src/tideup" \
    --create-dirs \
    --output "${TIDE_INSTALL_DIR}tideup" &&
    chmod +x "${TIDE_INSTALL_DIR}tideup"
}

ensure_tide_install_dir_is_not_in_path() {
  [[ ! ":${PATH}:" == *":${TIDE_INSTALL_DIR}:"* ]]
}

write_tide_path_in_bashrc_if_needed() {
  ensure_tide_install_dir_is_not_in_path &&
    cat <<HERE >>"${BASHRC_PATH}"

# tide
export TIDE_INSTALL_DIR="$TIDE_INSTALL_DIR"
export PATH="\${PATH}:\${TIDE_INSTALL_DIR}"
HERE
}

print_installation_status() {
  echo "tide installed in ${TIDE_INSTALL_DIR} and registered in \$PATH. Start a new shell or login to use."
}

main() {
  ensure_shell_is_bash &&
    install_tideup &&
    write_tide_path_in_bashrc_if_needed &&
    print_installation_status
}

main
